
class ApplicationController < Sinatra::Base
  register Sinatra::ActiveRecordExtension
  set :views, Proc.new { File.join(root, "../views/") }

  configure do                    #--------------- Session cookies allow a website to keep track of your movement from page to page for that specific session
    enable :sessions              #--------------- (from the time you log in to the time you log out or close the browser). Session cookies simply allow you
    set :session_secret, "secret" #--------------- to navigate through a site without repeatedly having to authenticate yourself on every new page you visit
  end                             #--------------- within the web application domain. Session cookies expire every time you log out or navigate away from
                                  #--------------- the website.




  get '/' do
    erb :home #render the app/views/home.erb
  end

  get '/registrations/signup' do  #--------------- render the sign-up form view which can be found in app/views/registrations/signup.erb

    erb :'/registrations/signup'
  end

  post '/registrations' do        #--------------- responsible for handling the POST request that is sent when a user hits 'submit' on the sign-up form.
    @user = User.new(name: params["name"], email: params["email"], password: params["password"]) # 1. gets the new user's info from the params hash
    @user.save                                                                                   # 2. creates/saves a new user
    session[:user_id] = @user.id                                                                 # 3. signs them in with autogenerated id from database

    redirect '/users/home'                                                                       # 4. redirects them somewhere else
  end

  get '/sessions/login' do      #--------------- responsible for rendering the login form view page in app/views/sessions/login.erb

    erb :'sessions/login'
  end

  post '/sessions' do           #--------------- responsible for receiving the POST request that gets sent when a user hits 'submit' on the login form
    @user = User.find_by(email: params[:email], password: params[:password]) # 1. grabs the user's info from the params hash
    if @user                                                                 # 2. looks to match that info against the existing entries in the user database
      session[:user_id] = @user.id
      redirect '/users/home'                                                 # 3. if a matching entry is found, signs the user in
    end
    redirect '/sessions/login'
  end

  get '/sessions/logout' do      #--------------- responsible for logging the user out by clearing the session hash.
    session.clear
    redirect '/'
  end

  get '/users/home' do            #---------------1. First this route finds the current user based on the ID value stored in the session hash

    @user = User.find(session[:user_id])#---------2. Then, it sets an instance variable, @user, equal to that found user, allowing us to access the current user in the corresponding view page.
    erb :'/users/home'            #---------------3. Finally it renders the user's homepage view.
  end
end
